# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Checkout code into Go module directory
        uses: actions/checkout@v2

      - name: Install golang migrate
        run: |
          version="v4.14.1" # replace with the version you want
          platform="linux" # replace with your platform, likely "linux" for Ubuntu in GitHub Actions
          curl -L "https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$platform-amd64.tar.gz" | tar xvz
          sudo mv migrate.$platform-amd64 /usr/local/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
