# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          id: go

      - name: Checkout code into Go module directory
        uses: actions/checkout@v2

      - name: Install golang migrate
        run: go get -v github.com/golang-migrate/migrate/v4/cmd/migrate && go install github.com/golang-migrate/migrate/v4/cmd/migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
